kind: Service
apiVersion: v1
metadata:
  name: trips-svc
  namespace: api
spec:
  selector:
    app: trips
  ports:
    - port: 80 # Default port for image
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: api
spec:
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: trips
        image: registrycum5425.azurecr.io/tripinsights/trips:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: sql        