kind: Service
apiVersion: v1
metadata:
  name: userprofile-svc
  namespace: api
spec:
  selector:
    app: userprofile
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: api
spec:
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: registrycum5425.azurecr.io/tripinsights/userprofile:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: sql