apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripinsights-poi
spec:
  selector:
    matchLabels:
      app: tripinsights-poi
  template:
    metadata:
      labels:
        app: tripinsights-poi
    spec:
      containers:
      - name: tripinsights-poi
        image: tripinsights-poi:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: SQL_USER
            value: sa
          - name: SQL_PASSWORD
            value: changeme
          - name: WEB_SERVER_BASE_URI
            value: sqlservercum5425.database.windows.net