kind: Service
apiVersion: v1
metadata:
  name: tripviewer-svc
  namespace: web
spec:
  selector:
    app: tripviewer
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: web
spec:
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registrycum5425.azurecr.io/tripinsights/tripviewer:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: USERPROFILE_API_ENDPOINT
            value: http://userprofile-svc.api:80
          - name: TRIPS_API_ENDPOINT
            value: http://trips-svc.api:80
