apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: api
spec:
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: registrycum5425.azurecr.io/tripinsights/userprofile:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: SQL_USER
            value: sa
          - name: SQL_PASSWORD
            value: changeme
          - name: SQL_SERVER
            value: sqlservercum5425.database.windows.net