kind: Service
apiVersion: v1
metadata:
  name: poi-svc
  namespace: api
spec:
  selector:
    app: poi
  ports:
    - port: 80 # Default port for image
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: api
spec:
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registrycum5425.azurecr.io/tripinsights/poi:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: sql