kind: Service
apiVersion: v1
metadata:
  name: user-java-svc
  namespace: api
spec:
  selector:
    app: user-java
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  namespace: api
spec:
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - name: user-java
        image: registrycum5425.azurecr.io/tripinsights/user-java:1.0
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: sql